checking ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,11 +1,6 @@
 on: [push, pull_request]
 name: CI
 jobs:
-  # ================
-  # TEST JOB
-  #   runs on every push and PR
-  #   runs 2x3 times (see matrix)
-  # ================
   test:
     name: Test
     strategy:
@@ -14,11 +9,23 @@ jobs:
         platform: [ubuntu-latest]
     runs-on: ${{ matrix.platform }}
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
       - name: Install Go
-        run: echo "Installing Go ${{ matrix.go-version }}"
+        uses: actions/setup-go@v5
+        with:
+          go-version: ${{ matrix.go-version }}
+
+      - name: Verify Go Version & Modules
+        run: |
+          go version
+          ls -la
+          cat go.mod || echo "go.mod not found"
 
       - name: Build
         run: go build -v -o /dev/null .
 
       - name: Test
         run: go test -v ./...
+
